// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    MyFooter: typeof import('./components/MyFooter.vue')['default']
    MyTest: typeof import('./components/nested/MyTest.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}

export { }
