// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default']
    GlobalSimpleButton: typeof import('./components/GlobalSimpleButton.vue')['default']
    MultiSelector: typeof import('./components/MultiSelector.vue')['default']
    OldSearchFilter: typeof import('./components/OldSearchFilter.vue')['default']
    TableVis: typeof import('./components/TableVis.vue')['default']
    TestUsersProps: typeof import('./components/TestUsersProps.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}

export { }
